# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formadmin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormAdmin(object):
    def setupUi(self, FormAdmin):
        FormAdmin.setObjectName("FormAdmin")
        FormAdmin.resize(792, 521)
        FormAdmin.setToolTip("")
        FormAdmin.setToolTipDuration(5)
        self.label_logo = QtWidgets.QLabel(FormAdmin)
        self.label_logo.setGeometry(QtCore.QRect(30, 20, 291, 61))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("resource/header_logon.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.groupPegawai = QtWidgets.QGroupBox(FormAdmin)
        self.groupPegawai.setGeometry(QtCore.QRect(20, 110, 371, 371))
        self.groupPegawai.setObjectName("groupPegawai")
        self.tabDataPegawai = QtWidgets.QTabWidget(self.groupPegawai)
        self.tabDataPegawai.setGeometry(QtCore.QRect(10, 20, 351, 341))
        self.tabDataPegawai.setObjectName("tabDataPegawai")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 324, 282))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tablePegawai = QtWidgets.QTableWidget(self.layoutWidget)
        self.tablePegawai.setObjectName("tablePegawai")
        self.tablePegawai.setColumnCount(0)
        self.tablePegawai.setRowCount(0)
        self.tablePegawai.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_5.addWidget(self.tablePegawai)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cari = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cari.setFont(font)
        self.label_cari.setObjectName("label_cari")
        self.verticalLayout.addWidget(self.label_cari)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linePencarian = QtWidgets.QLineEdit(self.layoutWidget)
        self.linePencarian.setObjectName("linePencarian")
        self.horizontalLayout.addWidget(self.linePencarian)
        self.cariButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cariButton.setObjectName("cariButton")
        self.horizontalLayout.addWidget(self.cariButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.refreshButton = QtWidgets.QPushButton(self.layoutWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_8.addWidget(self.refreshButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addLayout(self.verticalLayout_11)
        self.tabDataPegawai.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableLogLogin = QtWidgets.QTableWidget(self.tab_2)
        self.tableLogLogin.setGeometry(QtCore.QRect(10, 10, 325, 295))
        self.tableLogLogin.setColumnCount(0)
        self.tableLogLogin.setObjectName("tableLogLogin")
        self.tableLogLogin.setRowCount(0)
        self.tableLogLogin.horizontalHeader().setCascadingSectionResizes(True)
        self.tableLogLogin.horizontalHeader().setSortIndicatorShown(False)
        self.tableLogLogin.horizontalHeader().setStretchLastSection(False)
        self.tabDataPegawai.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableLogData = QtWidgets.QTableWidget(self.tab_3)
        self.tableLogData.setGeometry(QtCore.QRect(10, 10, 325, 295))
        self.tableLogData.setRowCount(0)
        self.tableLogData.setColumnCount(0)
        self.tableLogData.setObjectName("tableLogData")
        self.tableLogData.horizontalHeader().setCascadingSectionResizes(True)
        self.tabDataPegawai.addTab(self.tab_3, "")
        self.line = QtWidgets.QFrame(FormAdmin)
        self.line.setGeometry(QtCore.QRect(20, 90, 751, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(FormAdmin)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 110, 371, 371))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 70, 351, 46))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_nama = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nama.setFont(font)
        self.label_nama.setObjectName("label_nama")
        self.verticalLayout_2.addWidget(self.label_nama)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineNama = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineNama.setObjectName("lineNama")
        self.horizontalLayout_2.addWidget(self.lineNama)
        self.lineNama_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineNama_2.setObjectName("lineNama_2")
        self.horizontalLayout_2.addWidget(self.lineNama_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 171, 351, 46))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_alamat = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_alamat.setFont(font)
        self.label_alamat.setObjectName("label_alamat")
        self.verticalLayout_7.addWidget(self.label_alamat)
        self.lineAlamat = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineAlamat.setObjectName("lineAlamat")
        self.verticalLayout_7.addWidget(self.lineAlamat)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 220, 351, 44))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_kontak = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kontak.setFont(font)
        self.label_kontak.setObjectName("label_kontak")
        self.verticalLayout_10.addWidget(self.label_kontak)
        self.lineKontak = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineKontak.setObjectName("lineKontak")
        self.verticalLayout_10.addWidget(self.lineKontak)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 271, 351, 44))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_jabatan = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_jabatan.setFont(font)
        self.label_jabatan.setObjectName("label_jabatan")
        self.verticalLayout_6.addWidget(self.label_jabatan)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 351, 46))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_nik = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nik.setFont(font)
        self.label_nik.setObjectName("label_nik")
        self.verticalLayout_3.addWidget(self.label_nik)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineNIK = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineNIK.setObjectName("lineNIK")
        self.horizontalLayout_3.addWidget(self.lineNIK)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 120, 351, 46))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_password = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.verticalLayout_4.addWidget(self.label_password)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_password = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.line_password.setObjectName("line_password")
        self.horizontalLayout_4.addWidget(self.line_password)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 330, 351, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.hapusButton = QtWidgets.QPushButton(self.widget)
        self.hapusButton.setObjectName("hapusButton")
        self.horizontalLayout_5.addWidget(self.hapusButton)
        self.editButton = QtWidgets.QPushButton(self.widget)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout_5.addWidget(self.editButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.label_12 = QtWidgets.QLabel(FormAdmin)
        self.label_12.setGeometry(QtCore.QRect(630, 490, 151, 20))
        self.label_12.setObjectName("label_12")
        self.frame = QtWidgets.QFrame(FormAdmin)
        self.frame.setGeometry(QtCore.QRect(540, 10, 231, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_logout = QtWidgets.QLabel(self.frame)
        self.label_logout.setGeometry(QtCore.QRect(170, 50, 41, 16))
        self.label_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_logout.setObjectName("label_logout")
        self.button_logout = QtWidgets.QPushButton(self.frame)
        self.button_logout.setEnabled(True)
        self.button_logout.setGeometry(QtCore.QRect(170, 10, 41, 41))
        self.button_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_logout.setToolTip("")
        self.button_logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_logout.setIcon(icon)
        self.button_logout.setIconSize(QtCore.QSize(30, 30))
        self.button_logout.setFlat(True)
        self.button_logout.setObjectName("button_logout")
        self.layoutWidget6 = QtWidgets.QWidget(self.frame)
        self.layoutWidget6.setGeometry(QtCore.QRect(70, 10, 80, 53))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_nama_adm = QtWidgets.QLabel(self.layoutWidget6)
        self.label_nama_adm.setObjectName("label_nama_adm")
        self.verticalLayout_14.addWidget(self.label_nama_adm)
        self.label_nik_adm = QtWidgets.QLabel(self.layoutWidget6)
        self.label_nik_adm.setObjectName("label_nik_adm")
        self.verticalLayout_14.addWidget(self.label_nik_adm)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.label_photo = QtWidgets.QLabel(self.frame)
        self.label_photo.setGeometry(QtCore.QRect(11, 11, 53, 53))
        self.label_photo.setAutoFillBackground(True)
        self.label_photo.setText("")
        self.label_photo.setPixmap(QtGui.QPixmap("resource/photo 64x64.png"))
        self.label_photo.setScaledContents(True)
        self.label_photo.setWordWrap(True)
        self.label_photo.setObjectName("label_photo")

        self.retranslateUi(FormAdmin)
        self.tabDataPegawai.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormAdmin)

    def retranslateUi(self, FormAdmin):
        _translate = QtCore.QCoreApplication.translate
        FormAdmin.setWindowTitle(_translate("FormAdmin", "Telkom Medika"))
        self.groupPegawai.setTitle(_translate("FormAdmin", "Data Pegawai"))
        self.label_cari.setText(_translate("FormAdmin", "Pencarian"))
        self.cariButton.setText(_translate("FormAdmin", "Cari"))
        self.refreshButton.setText(_translate("FormAdmin", "Refresh"))
        self.tabDataPegawai.setTabText(self.tabDataPegawai.indexOf(self.tab), _translate("FormAdmin", "Daftar Pegawai"))
        self.tabDataPegawai.setTabText(self.tabDataPegawai.indexOf(self.tab_2), _translate("FormAdmin", "Log Login Pegawai"))
        self.tabDataPegawai.setTabText(self.tabDataPegawai.indexOf(self.tab_3), _translate("FormAdmin", "Log Data Pasien"))
        self.groupBox_2.setTitle(_translate("FormAdmin", "Data Baru"))
        self.label_nama.setText(_translate("FormAdmin", "Nama Pegawai"))
        self.label_alamat.setText(_translate("FormAdmin", "Alamat"))
        self.label_kontak.setText(_translate("FormAdmin", "No.Handphone"))
        self.lineKontak.setText(_translate("FormAdmin", "+62"))
        self.label_jabatan.setText(_translate("FormAdmin", "Jabatan"))
        self.comboBox.setItemText(0, _translate("FormAdmin", "-"))
        self.comboBox.setItemText(1, _translate("FormAdmin", "Admin"))
        self.comboBox.setItemText(2, _translate("FormAdmin", "Dokter"))
        self.comboBox.setItemText(3, _translate("FormAdmin", "Karyawan"))
        self.label_nik.setText(_translate("FormAdmin", "NIK"))
        self.label_password.setText(_translate("FormAdmin", "Password"))
        self.hapusButton.setText(_translate("FormAdmin", "Hapus"))
        self.editButton.setText(_translate("FormAdmin", "Edit"))
        self.pushButton_6.setText(_translate("FormAdmin", "Clear"))
        self.pushButton_3.setText(_translate("FormAdmin", "Tambahkan"))
        self.label_12.setText(_translate("FormAdmin", "Telkom Medika. 2020"))
        self.label_logout.setText(_translate("FormAdmin", "Logout"))
        self.label_nama_adm.setText(_translate("FormAdmin", "[Nama Pegawai]"))
        self.label_nik_adm.setText(_translate("FormAdmin", "[NIK]"))
        self.label_14.setText(_translate("FormAdmin", "Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormAdmin = QtWidgets.QWidget()
    ui = Ui_FormAdmin()
    ui.setupUi(FormAdmin)
    FormAdmin.show()
    sys.exit(app.exec_())

