# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formpendaftar.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormPendaftar(object):
    def setupUi(self, FormPendaftar):
        FormPendaftar.setObjectName("FormPendaftar")
        FormPendaftar.resize(792, 578)
        self.groupPasien = QtWidgets.QGroupBox(FormPendaftar)
        self.groupPasien.setGeometry(QtCore.QRect(20, 110, 371, 421))
        self.groupPasien.setObjectName("groupPasien")
        self.widget = QtWidgets.QWidget(self.groupPasien)
        self.widget.setGeometry(QtCore.QRect(10, 20, 351, 391))
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tablePasien = QtWidgets.QTableWidget(self.widget)
        self.tablePasien.setObjectName("tablePasien")
        self.tablePasien.setColumnCount(0)
        self.tablePasien.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tablePasien)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cari = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cari.setFont(font)
        self.label_cari.setObjectName("label_cari")
        self.verticalLayout.addWidget(self.label_cari)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linePencarian = QtWidgets.QLineEdit(self.widget)
        self.linePencarian.setObjectName("linePencarian")
        self.horizontalLayout.addWidget(self.linePencarian)
        self.cariButton = QtWidgets.QPushButton(self.widget)
        self.cariButton.setObjectName("cariButton")
        self.horizontalLayout.addWidget(self.cariButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.refreshButton = QtWidgets.QPushButton(self.widget)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout_9.addWidget(self.refreshButton)
        self.line = QtWidgets.QFrame(FormPendaftar)
        self.line.setGeometry(QtCore.QRect(20, 90, 751, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(FormPendaftar)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 110, 371, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 380, 351, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.hapusButton = QtWidgets.QPushButton(self.layoutWidget)
        self.hapusButton.setObjectName("hapusButton")
        self.horizontalLayout_6.addWidget(self.hapusButton)
        self.editButton = QtWidgets.QPushButton(self.layoutWidget)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout_6.addWidget(self.editButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 351, 299))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_nama = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nama.setFont(font)
        self.label_nama.setObjectName("label_nama")
        self.verticalLayout_2.addWidget(self.label_nama)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineNama = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineNama.setObjectName("lineNama")
        self.horizontalLayout_2.addWidget(self.lineNama)
        self.lineNama_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineNama_2.setObjectName("lineNama_2")
        self.horizontalLayout_2.addWidget(self.lineNama_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineTempatLahir = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineTempatLahir.setObjectName("lineTempatLahir")
        self.horizontalLayout_3.addWidget(self.lineTempatLahir)
        self.dateLahir = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateLahir.setReadOnly(False)
        self.dateLahir.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateLahir.setCalendarPopup(True)
        self.dateLahir.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateLahir.setObjectName("dateLahir")
        self.horizontalLayout_3.addWidget(self.dateLahir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioLaki = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioLaki.setInputMethodHints(QtCore.Qt.ImhNone)
        self.radioLaki.setObjectName("radioLaki")
        self.horizontalLayout_4.addWidget(self.radioLaki)
        self.radioLadies = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioLadies.setInputMethodHints(QtCore.Qt.ImhNone)
        self.radioLadies.setObjectName("radioLadies")
        self.horizontalLayout_4.addWidget(self.radioLadies)
        self.radioHeli = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioHeli.setInputMethodHints(QtCore.Qt.ImhNone)
        self.radioHeli.setObjectName("radioHeli")
        self.horizontalLayout_4.addWidget(self.radioHeli)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.comboGoldar = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboGoldar.setObjectName("comboGoldar")
        self.comboGoldar.addItem("")
        self.comboGoldar.addItem("")
        self.comboGoldar.addItem("")
        self.comboGoldar.addItem("")
        self.comboGoldar.addItem("")
        self.verticalLayout_5.addWidget(self.comboGoldar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.lineAlamat = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineAlamat.setObjectName("lineAlamat")
        self.verticalLayout_7.addWidget(self.lineAlamat)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_10.addWidget(self.lineEdit_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.label_12 = QtWidgets.QLabel(FormPendaftar)
        self.label_12.setGeometry(QtCore.QRect(630, 540, 151, 20))
        self.label_12.setObjectName("label_12")
        self.label_logo = QtWidgets.QLabel(FormPendaftar)
        self.label_logo.setGeometry(QtCore.QRect(20, 20, 291, 61))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("resource/logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.frame = QtWidgets.QFrame(FormPendaftar)
        self.frame.setGeometry(QtCore.QRect(540, 10, 231, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_logout = QtWidgets.QLabel(self.frame)
        self.label_logout.setGeometry(QtCore.QRect(170, 50, 41, 16))
        self.label_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_logout.setObjectName("label_logout")
        self.button_logout = QtWidgets.QPushButton(self.frame)
        self.button_logout.setEnabled(True)
        self.button_logout.setGeometry(QtCore.QRect(170, 10, 41, 41))
        self.button_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_logout.setToolTip("")
        self.button_logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_logout.setIcon(icon)
        self.button_logout.setIconSize(QtCore.QSize(30, 30))
        self.button_logout.setFlat(True)
        self.button_logout.setObjectName("button_logout")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(70, 10, 80, 53))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_nama_adm = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_nama_adm.setObjectName("label_nama_adm")
        self.verticalLayout_14.addWidget(self.label_nama_adm)
        self.label_nik_adm = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_nik_adm.setObjectName("label_nik_adm")
        self.verticalLayout_14.addWidget(self.label_nik_adm)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.label_photo = QtWidgets.QLabel(self.frame)
        self.label_photo.setGeometry(QtCore.QRect(11, 11, 53, 53))
        self.label_photo.setAutoFillBackground(True)
        self.label_photo.setText("")
        self.label_photo.setPixmap(QtGui.QPixmap("resource/photo 64x64.png"))
        self.label_photo.setScaledContents(True)
        self.label_photo.setWordWrap(True)
        self.label_photo.setObjectName("label_photo")

        self.retranslateUi(FormPendaftar)
        QtCore.QMetaObject.connectSlotsByName(FormPendaftar)

    def retranslateUi(self, FormPendaftar):
        _translate = QtCore.QCoreApplication.translate
        FormPendaftar.setWindowTitle(_translate("FormPendaftar", "Puskesmas Kasih Bunda"))
        self.groupPasien.setTitle(_translate("FormPendaftar", "Data Pasien"))
        self.label_cari.setText(_translate("FormPendaftar", "Pencarian"))
        self.cariButton.setText(_translate("FormPendaftar", "Cari"))
        self.refreshButton.setText(_translate("FormPendaftar", "Refresh"))
        self.groupBox_2.setTitle(_translate("FormPendaftar", "Data Baru"))
        self.hapusButton.setText(_translate("FormPendaftar", "Hapus"))
        self.editButton.setText(_translate("FormPendaftar", "Edit"))
        self.pushButton_6.setText(_translate("FormPendaftar", "Clear"))
        self.pushButton_3.setText(_translate("FormPendaftar", "Tambahkan"))
        self.label_nama.setText(_translate("FormPendaftar", "Nama Pasien"))
        self.label_3.setText(_translate("FormPendaftar", "Tempat/Tanggal Lahir"))
        self.dateLahir.setDisplayFormat(_translate("FormPendaftar", "yyyy-MM-dd"))
        self.label_4.setText(_translate("FormPendaftar", "Jenis Kelamin"))
        self.radioLaki.setText(_translate("FormPendaftar", "Laki-laki"))
        self.radioLadies.setText(_translate("FormPendaftar", "Perempuan"))
        self.radioHeli.setText(_translate("FormPendaftar", "Apache Attack Heli"))
        self.label_5.setText(_translate("FormPendaftar", "Gol. Darah"))
        self.comboGoldar.setItemText(0, _translate("FormPendaftar", "-"))
        self.comboGoldar.setItemText(1, _translate("FormPendaftar", "A"))
        self.comboGoldar.setItemText(2, _translate("FormPendaftar", "B"))
        self.comboGoldar.setItemText(3, _translate("FormPendaftar", "AB"))
        self.comboGoldar.setItemText(4, _translate("FormPendaftar", "O"))
        self.label_6.setText(_translate("FormPendaftar", "Alamat"))
        self.label_10.setText(_translate("FormPendaftar", "No.Handphone"))
        self.lineEdit_7.setText(_translate("FormPendaftar", "+62"))
        self.label_7.setText(_translate("FormPendaftar", "Keperluan"))
        self.comboBox.setItemText(0, _translate("FormPendaftar", "-"))
        self.comboBox.setItemText(1, _translate("FormPendaftar", "Dokter Umum"))
        self.comboBox.setItemText(2, _translate("FormPendaftar", "Dokter Kandungan"))
        self.comboBox.setItemText(3, _translate("FormPendaftar", "Dokter THT"))
        self.label_12.setText(_translate("FormPendaftar", "Puskesmas Kasih Bunda. 2020"))
        self.label_logout.setText(_translate("FormPendaftar", "Logout"))
        self.label_nama_adm.setText(_translate("FormPendaftar", "[Nama Pegawai]"))
        self.label_nik_adm.setText(_translate("FormPendaftar", "[NIK]"))
        self.label_14.setText(_translate("FormPendaftar", "Karyawan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormPendaftar = QtWidgets.QWidget()
    ui = Ui_FormPendaftar()
    ui.setupUi(FormPendaftar)
    FormPendaftar.show()
    sys.exit(app.exec_())

