# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formdokter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormDokter(object):
    def setupUi(self, FormDokter):
        FormDokter.setObjectName("FormDokter")
        FormDokter.resize(791, 569)
        self.line = QtWidgets.QFrame(FormDokter)
        self.line.setGeometry(QtCore.QRect(20, 90, 751, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(FormDokter)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 110, 371, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_goldar = QtWidgets.QLabel(self.groupBox_2)
        self.label_goldar.setGeometry(QtCore.QRect(245, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_goldar.setFont(font)
        self.label_goldar.setObjectName("label_goldar")
        self.lineGoldar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineGoldar.setEnabled(False)
        self.lineGoldar.setGeometry(QtCore.QRect(310, 79, 51, 20))
        self.lineGoldar.setObjectName("lineGoldar")
        self.lineGender = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineGender.setEnabled(False)
        self.lineGender.setGeometry(QtCore.QRect(104, 79, 136, 20))
        self.lineGender.setText("")
        self.lineGender.setObjectName("lineGender")
        self.label_gender = QtWidgets.QLabel(self.groupBox_2)
        self.label_gender.setGeometry(QtCore.QRect(12, 80, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_gender.setFont(font)
        self.label_gender.setObjectName("label_gender")
        self.label_nama = QtWidgets.QLabel(self.groupBox_2)
        self.label_nama.setGeometry(QtCore.QRect(12, 51, 74, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nama.setFont(font)
        self.label_nama.setObjectName("label_nama")
        self.lineNama = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineNama.setEnabled(False)
        self.lineNama.setGeometry(QtCore.QRect(104, 50, 257, 20))
        self.lineNama.setObjectName("lineNama")
        self.lineId = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineId.setEnabled(False)
        self.lineId.setGeometry(QtCore.QRect(104, 21, 257, 20))
        self.lineId.setObjectName("lineId")
        self.label_nomor = QtWidgets.QLabel(self.groupBox_2)
        self.label_nomor.setGeometry(QtCore.QRect(13, 21, 79, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nomor.setFont(font)
        self.label_nomor.setObjectName("label_nomor")
        self.lineRiwayat = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.lineRiwayat.setGeometry(QtCore.QRect(10, 130, 351, 241))
        self.lineRiwayat.setObjectName("lineRiwayat")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(120, 380, 239, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hapusButton = QtWidgets.QPushButton(self.widget)
        self.hapusButton.setObjectName("hapusButton")
        self.horizontalLayout_2.addWidget(self.hapusButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.label_riwayat = QtWidgets.QLabel(self.groupBox_2)
        self.label_riwayat.setGeometry(QtCore.QRect(11, 111, 108, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_riwayat.setFont(font)
        self.label_riwayat.setObjectName("label_riwayat")
        self.label_12 = QtWidgets.QLabel(FormDokter)
        self.label_12.setGeometry(QtCore.QRect(630, 540, 151, 20))
        self.label_12.setObjectName("label_12")
        self.groupPasien = QtWidgets.QGroupBox(FormDokter)
        self.groupPasien.setGeometry(QtCore.QRect(20, 110, 371, 421))
        self.groupPasien.setObjectName("groupPasien")
        self.widget1 = QtWidgets.QWidget(self.groupPasien)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 351, 391))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tablePasien = QtWidgets.QTableWidget(self.widget1)
        self.tablePasien.setObjectName("tablePasien")
        self.tablePasien.setColumnCount(0)
        self.tablePasien.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tablePasien)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cari = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cari.setFont(font)
        self.label_cari.setObjectName("label_cari")
        self.verticalLayout.addWidget(self.label_cari)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linePencarian = QtWidgets.QLineEdit(self.widget1)
        self.linePencarian.setObjectName("linePencarian")
        self.horizontalLayout.addWidget(self.linePencarian)
        self.cariButton = QtWidgets.QPushButton(self.widget1)
        self.cariButton.setObjectName("cariButton")
        self.horizontalLayout.addWidget(self.cariButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.refreshButton = QtWidgets.QPushButton(self.widget1)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_8.addWidget(self.refreshButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.verticalLayout_11)
        self.frame = QtWidgets.QFrame(FormDokter)
        self.frame.setGeometry(QtCore.QRect(540, 10, 231, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_logout = QtWidgets.QLabel(self.frame)
        self.label_logout.setGeometry(QtCore.QRect(170, 50, 41, 16))
        self.label_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_logout.setObjectName("label_logout")
        self.button_logout = QtWidgets.QPushButton(self.frame)
        self.button_logout.setEnabled(True)
        self.button_logout.setGeometry(QtCore.QRect(170, 10, 41, 41))
        self.button_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_logout.setToolTip("")
        self.button_logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_logout.setIcon(icon)
        self.button_logout.setIconSize(QtCore.QSize(30, 30))
        self.button_logout.setFlat(True)
        self.button_logout.setObjectName("button_logout")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 10, 101, 53))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_nama_adm = QtWidgets.QLabel(self.layoutWidget)
        self.label_nama_adm.setObjectName("label_nama_adm")
        self.verticalLayout_14.addWidget(self.label_nama_adm)
        self.label_nik_adm = QtWidgets.QLabel(self.layoutWidget)
        self.label_nik_adm.setObjectName("label_nik_adm")
        self.verticalLayout_14.addWidget(self.label_nik_adm)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.label_photo = QtWidgets.QLabel(self.frame)
        self.label_photo.setGeometry(QtCore.QRect(11, 11, 53, 53))
        self.label_photo.setAutoFillBackground(True)
        self.label_photo.setText("")
        self.label_photo.setPixmap(QtGui.QPixmap("resource/photo 64x64.png"))
        self.label_photo.setScaledContents(True)
        self.label_photo.setWordWrap(True)
        self.label_photo.setObjectName("label_photo")
        self.label_logo = QtWidgets.QLabel(FormDokter)
        self.label_logo.setGeometry(QtCore.QRect(20, 20, 291, 61))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("resource/logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")

        self.retranslateUi(FormDokter)
        QtCore.QMetaObject.connectSlotsByName(FormDokter)

    def retranslateUi(self, FormDokter):
        _translate = QtCore.QCoreApplication.translate
        FormDokter.setWindowTitle(_translate("FormDokter", "Form"))
        self.groupBox_2.setTitle(_translate("FormDokter", "Data Pasien"))
        self.label_goldar.setText(_translate("FormDokter", "Gol. Darah"))
        self.label_gender.setText(_translate("FormDokter", "Jenis Kelamin"))
        self.label_nama.setText(_translate("FormDokter", "Nama Pasien"))
        self.label_nomor.setText(_translate("FormDokter", "ID Pasien"))
        self.hapusButton.setText(_translate("FormDokter", "Hapus"))
        self.pushButton_6.setText(_translate("FormDokter", "Clear"))
        self.pushButton_3.setText(_translate("FormDokter", "Update"))
        self.label_riwayat.setText(_translate("FormDokter", "Riwayat Kesehatan"))
        self.label_12.setText(_translate("FormDokter", "Puskesmas Kasih Bunda. 2020"))
        self.groupPasien.setTitle(_translate("FormDokter", "Data Pasien"))
        self.label_cari.setText(_translate("FormDokter", "Pencarian"))
        self.cariButton.setText(_translate("FormDokter", "Cari"))
        self.refreshButton.setText(_translate("FormDokter", "Refresh"))
        self.label_logout.setText(_translate("FormDokter", "Logout"))
        self.label_nama_adm.setText(_translate("FormDokter", "[Nama Pegawai]"))
        self.label_nik_adm.setText(_translate("FormDokter", "[NIK]"))
        self.label_14.setText(_translate("FormDokter", "[Spesialisasi]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormDokter = QtWidgets.QWidget()
    ui = Ui_FormDokter()
    ui.setupUi(FormDokter)
    FormDokter.show()
    sys.exit(app.exec_())

